<b>Problem Statement : Hospital Patient Data Analysis</b>
<br>
<u>Context:<br></u>

A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

In [1]:
import pandas as pd
import numpy as np

In [2]:
patient_details=pd.read_csv("C:/Users/shanm/Python_Practice/Datasets/Patient_Data.csv")
patient_details

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [3]:
# Task 1
patient_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [4]:
# Task 2
selected4_columns = patient_details.loc[:,['PatientID', 'Department', 'Doctor', 'BillAmount']]
selected4_columns

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [5]:
#Task 3
dropped2_columns = patient_details.drop(['ReceptionistID','CheckInTime'],
                                       axis=1,
                                       inplace=True)
patient_details

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [40]:
# Task 4.Use groupby to find total bill amount per department
group = patient_details.groupby('Department')
total_bill = group['BillAmount'].sum()
total_bill

Department
Cardiology     11200.000000
Dermatology     6233.333333
Neurology       6233.333333
Orthopedics     7500.000000
Name: BillAmount, dtype: float64

In [41]:
#Task  5.Remove duplicate patient records based on PatientID.
duplicateRemoved = patient_details.drop_duplicates(subset=['PatientID'],inplace=True)
patient_details

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [42]:
# Task 6.Fill missing BillAmount values with the mean bill amount.
billMean = patient_details['BillAmount'].mean()
print("Mean Amount:", billMean)
patient_details.fillna({
    'BillAmount' : billMean
    },inplace=True)
patient_details

Mean Amount: 6233.333333333333

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [16]:
# 7.	Merge the billing dataset with patient dataset on PatientID.

In [18]:
billing_data = pd.read_csv("C:/Users/shanm/Python_Practice/Datasets/Billing_Data.csv")
billing_data

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [20]:
merged = pd.merge(patient_details,billing_data, on="PatientID")
merged

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [43]:
# 8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise)    

additional = {
    'PatientID' : [106,107],
    'Name' : ['Shanmu','Kozhi'],
    'Department' : ['Dermatology','Orthopedics'],
    'Doctor' : ['Dr. Rose','Dr. Lee'],
    'BillAmount' : [7000,1000],
    'InsuranceCovered' : [3000,0],
    'FinalAmount' : [4000,1000],
}
new_Patients = pd.DataFrame(additional,index=[6,7])
new_Patients

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
6,106,Shanmu,Dermatology,Dr. Rose,7000,3000,4000
7,107,Kozhi,Orthopedics,Dr. Lee,1000,0,1000

In [48]:
patients_Current_week = pd.concat([merged,new_Patients] )
patients_Current_week

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
6,106,Shanmu,Dermatology,Dr. Rose,7000.000000,3000,4000
7,107,Kozhi,Orthopedics,Dr. Lee,1000.000000,0,1000

In [51]:
# 9.Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
billing_Cat = pd.concat([patients_Current_week["InsuranceCovered"], patients_Current_week["FinalAmount"]], axis=1)
billing_Cat

   InsuranceCovered  FinalAmount
0              2000         3000
1              1500         3500
2              2500         5000
3              3000         3200
4              1000         4000
6              3000         4000
7                 0         1000

## Insights

In [55]:
Final_Cleaned_Dataset = patients_Current_week
patients_Current_week

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
6,106,Shanmu,Dermatology,Dr. Rose,7000.000000,3000,4000
7,107,Kozhi,Orthopedics,Dr. Lee,1000.000000,0,1000

In [57]:
###  Department wise revenue
group = patients_Current_week.groupby('Department')
total_bill = group['BillAmount'].sum()
total_bill

Department
Cardiology     11200.000000
Dermatology    13233.333333
Neurology       6233.333333
Orthopedics     8500.000000
Name: BillAmount, dtype: float64

In [58]:
#### Doctor's performance

group = patients_Current_week.groupby('Doctor')
total_bill = group['BillAmount'].sum()
total_bill

Doctor
Dr. John      6233.333333
Dr. Lee       8500.000000
Dr. Rose     13233.333333
Dr. Smith    11200.000000
Name: BillAmount, dtype: float64