# Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [28]:
lst=[1,2,3,4,5]
lst.append(6)
print("After Append :",lst)
lst.extend([7,8,9,1])
print("After extend :",lst)
lst.insert(0,999)
print("After insert :",lst)
lst.remove(999)
print("After remove :",lst)
lst.pop(2)
print("After pop    :",lst)
ind=lst.index(5)
print("Index of 5   :",ind)
cnt=lst.count(1)
print("count of 1   :",cnt)
lst.sort()
print("After sort   :",lst)
lst.reverse()
print("After reverse:",lst)
lst.sort(reverse=True)
print("After reversing using sort:",lst)
lst.clear()
lst

After Append : [1, 2, 3, 4, 5, 6]
After extend : [1, 2, 3, 4, 5, 6, 7, 8, 9, 1]
After insert : [999, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1]
After remove : [1, 2, 3, 4, 5, 6, 7, 8, 9, 1]
After pop    : [1, 2, 4, 5, 6, 7, 8, 9, 1]
Index of 5   : 3
count of 1   : 2
After sort   : [1, 1, 2, 4, 5, 6, 7, 8, 9]
After reverse: [9, 8, 7, 6, 5, 4, 2, 1, 1]
After reversing using sort: [9, 8, 7, 6, 5, 4, 2, 1, 1]

[]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [32]:
tup=('Shan','love','Kozhi')

# we can't change values of a tuple since it is an immutable data type.Try changing the second name in the tuple will gives error

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [36]:
set={1,1,2,2,3,4}
set

# Set is an unordered collection of unique elements. As per definition of set,python automatically removes duplicate values.Set in python are implemented using hash tables
#If you try to insert a duplicate, Python sees that the hash already exists and simply ignores the new one.

{1, 2, 3, 4}

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [41]:
dict={
    'name': 'Shan',
    'age':23,
    'city': 'Chennai'
}
dict['age']=24
dict['email']='abc@gmail.com'
dict

{'name': 'Shan', 'age': 24, 'city': 'Chennai', 'email': 'abc@gmail.com'}

5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [44]:
age=int(input("Enter age to be validated:"))
if age>=18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter age to be validated: 2

Not eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [45]:
mark=int(input("Enter mark:"))
if mark>=90:
    grade='A'
elif mark>75 and mark<89:
    grade='B'
elif mark>50 and mark<74:
    grade='C'
else:
    grade="Fail"

print(f"Grade of {mark} is :",grade)

Enter mark: 56

Grade of 56 is : C

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [54]:
number=-9
if number>0:
    if number%2==0:
        print(f"{number} is a Positive even number")
    else:
        print(f"{number} is a Positive odd number")

else:
    if number<0:
        print(f"{number} is a negative number")
    elif number==0:
        print("number==zero")

-9 is a negative number

# Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [16]:
import numpy as np
scalar = np.array(5)
print("A scalar using np.array(5) :",scalar)

oneD_array=np.array([1,2,3,4,5])
print("A 1D array with values 1 to 5 :",oneD_array)

twoD_array=np.arange(10,70,10)
reshaped=twoD_array.reshape(2,3)
print("2*3 2D array :",reshaped)

A scalar using np.array(5) : 5
A 1D array with values 1 to 5 : [1 2 3 4 5]
2*3 2D array : [[10 20 30]
 [40 50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [17]:
fourD_array=np.random.randint(0,101,size=(4,4))
print(" 4x4 Numpy array of random integers :",fourD_array)

 4x4 Numpy array of random integers : [[26  6 20 23]
 [89 80 53 53]
 [77 85 89 60]
 [99 63 22 50]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'

In [19]:
nArray=np.random.randint(0,10,size=(3,3))
print(" 2D numpy array of shape (3x3) :",nArray)

 2D numpy array of shape (3x3) : [[4 2 1]
 [7 6 1]
 [9 9 2]]

In [21]:
import pandas as pd
arrFrame=pd.DataFrame(nArray,columns=['A','B','C'])
arrFrame

   A  B  C
0  4  2  1
1  7  6  1
2  9  9  2

# Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [45]:
data={
    'Name':['Shan','Shan','Sahana','Brindha','Dhaarani','Raji','Karuna','Nidhi','Mari','Eswari'],
    'Age':[24,24,13,16,24,47,52,25,30,67],
    'City':['Jkm','Jkm','Kmu','Banglore','Chennai','Jkm','Kmu','Banglore','Jkm','Chennai'],
    'Salary': [np.nan,np.nan,7800,np.nan,10000,7800,13000,6000,10000,np.nan]
}
dframe=pd.DataFrame(data)
dframe

       Name  Age      City   Salary
0      Shan   24       Jkm      NaN
1      Shan   24       Jkm      NaN
2    Sahana   13       Kmu   7800.0
3   Brindha   16  Banglore      NaN
4  Dhaarani   24   Chennai  10000.0
5      Raji   47       Jkm   7800.0
6    Karuna   52       Kmu  13000.0
7     Nidhi   25  Banglore   6000.0
8      Mari   30       Jkm  10000.0
9    Eswari   67   Chennai      NaN

In [46]:
# Use .info(), .describe()
dframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  6 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [47]:
dframe.describe()

             Age        Salary
count  10.000000      6.000000
mean   32.200000   9100.000000
std    17.357675   2442.130218
min    13.000000   6000.000000
25%    24.000000   7800.000000
50%    24.500000   8900.000000
75%    42.750000  10000.000000
max    67.000000  13000.000000

In [48]:
# Select 'Name' and 'City' columns

dname=dframe.loc[:,['Name','City']]
dname

       Name      City
0      Shan       Jkm
1      Shan       Jkm
2    Sahana       Kmu
3   Brindha  Banglore
4  Dhaarani   Chennai
5      Raji       Jkm
6    Karuna       Kmu
7     Nidhi  Banglore
8      Mari       Jkm
9    Eswari   Chennai

In [49]:
#  Drop 'City' column
dframe.drop('City',
            axis=1,
            inplace=True)
dframe

       Name  Age   Salary
0      Shan   24      NaN
1      Shan   24      NaN
2    Sahana   13   7800.0
3   Brindha   16      NaN
4  Dhaarani   24  10000.0
5      Raji   47   7800.0
6    Karuna   52  13000.0
7     Nidhi   25   6000.0
8      Mari   30  10000.0
9    Eswari   67      NaN

In [50]:
avg_a=dframe['Salary'].agg('mean')
avg_a

9100.0

In [51]:
dframe.fillna({
    'Salary':avg_a
},inplace=True)
dframe

       Name  Age   Salary
0      Shan   24   9100.0
1      Shan   24   9100.0
2    Sahana   13   7800.0
3   Brindha   16   9100.0
4  Dhaarani   24  10000.0
5      Raji   47   7800.0
6    Karuna   52  13000.0
7     Nidhi   25   6000.0
8      Mari   30  10000.0
9    Eswari   67   9100.0

In [54]:
# - Remove any duplicate rows
dframe.drop_duplicates
dframe

       Name  Age   Salary
0      Shan   24   9100.0
2    Sahana   13   7800.0
3   Brindha   16   9100.0
4  Dhaarani   24  10000.0
5      Raji   47   7800.0
6    Karuna   52  13000.0
7     Nidhi   25   6000.0
8      Mari   30  10000.0
9    Eswari   67   9100.0